# Generated by Django 5.1.6 on 2025-06-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_comment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
